apiVersion: apps/v1
kind: Deployment
metadata:
  name: masterdata-service
spec:
  selector:
    matchLabels:
      app: masterdata-service
  replicas: 1
  template:
    metadata:
      labels:
        app: masterdata-service
    spec:
      containers:
        - name: masterdata-service
          image: ctharinda/masterdata-service:latest

---
apiVersion: v1
kind: Service
metadata:
  name: masterdata-service
spec:
  selector:
    app: masterdata-service
  ports:
    - name: http
      port: 8180
      nodePort: 30180
  type: NodePort
