apiVersion: apps/v1
kind: Deployment
metadata:
  name: naming-server
spec:
  selector:
    matchLabels:
      app: naming-server
  replicas: 1
  template:
    metadata:
      labels:
        app: naming-server
    spec:
      containers:
        - name: naming-server
          image: ctharinda/naming-server:latest

---
apiVersion: v1
kind: Service
metadata:
  name: naming-server
spec:
  selector:
    app: naming-server
  ports:
    - name: http
      port: 8761
  type: ClusterIP
