apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          env:
            - name: POSTGRES_DB
              value: application_service
            - name: POSTGRES_PASSWORD
              value: 1s@secret
            - name: POSTGRES_USER
              value: app_user
          volumeMounts:
            - name: postgres-script-volume-mount
              mountPath: /docker-entrypoint-initdb.d/
      volumes:
        - name: postgres-script-volume-mount
          persistentVolumeClaim:
            claimName: postgres-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app: postgres
  ports:
    - name: http
      port: 5432
  type: ClusterIP
