apiVersion: apps/v1
kind: Deployment
metadata:
  name: zipkin-service
spec:
  selector:
    matchLabels:
      app: zipkin-service
  replicas: 1
  template:
    metadata:
      labels:
        app: zipkin-service
    spec:
      containers:
        - name: zipkin-service
          image: openzipkin/zipkin:latest

---
apiVersion: v1
kind: Service
metadata:
  name: zipkin-service
spec:
  selector:
    app: zipkin-service
  ports:
    - name: http
      port: 9411
      nodePort: 30411
  type: NodePort
